name: pipeline

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, reopened, edited, synchronize, ready_for_review]
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pipeline-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/publish.yml
    secrets: inherit
